"""initial migration

Revision ID: 488b81e5e228
Revises: 
Create Date: 2024-09-02 20:45:20.029730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '488b81e5e228'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charity_sphere')
    op.drop_table('recipients')
    op.drop_index('ix_fundraising_id', table_name='fundraising')
    op.drop_table('fundraising')
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_table('posts')
    op.drop_table('donors')
    op.drop_table('users')
    op.drop_index('ix_complaints_id', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_funds_id', table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('funds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='funds_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_funds_id', 'funds', ['id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='complaints_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='complaints_pkey')
    )
    op.create_index('ix_complaints_id', 'complaints', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_pin_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_pin_code_salt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('donors',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='donors_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='donors_pkey')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='posts_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_table('fundraising',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'published', 'completed', name='status_enum'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='fundraising_fund_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fundraising_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fundraising_pkey')
    )
    op.create_index('ix_fundraising_id', 'fundraising', ['id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='recipients_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipients_pkey'),
    sa.UniqueConstraint('email', name='recipients_email_key')
    )
    op.create_table('charity_sphere',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='charity_sphere_pkey')
    )
    # ### end Alembic commands ###
