"""end jule init

Revision ID: 80bb10d0e2d0
Revises: 436aff625488
Create Date: 2025-07-30 20:11:14.723455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bb10d0e2d0'
down_revision: Union[str, None] = '436aff625488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_entity_relations', schema=None) as batch_op:
        batch_op.drop_constraint('user_entity_relations_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.drop_constraint('user_meta_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('user_tokens_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tokens_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_meta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_meta_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_entity_relations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_entity_relations_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
