"""added tokens and sms-code

Revision ID: eef44a51a168
Revises: 0de65aae70b8
Create Date: 2025-06-07 16:55:40.972986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef44a51a168'
down_revision: Union[str, None] = '0de65aae70b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum('helping', 'getting help', name="user_role_enum")
user_role_enum.create(op.get_bind(), checkfirst=True)
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spheres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_phone'), ['phone'], unique=False)

    op.create_table('company_spheres',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'sphere_id')
    )
    op.create_table('foundation_spheres',
    sa.Column('foundation_id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foundation_id'], ['foundations.id'], ),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.PrimaryKeyConstraint('foundation_id', 'sphere_id')
    )
    op.create_table('user_spheres',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sphere_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('helping', 'getting help', name='user_role_enum'), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('role')

    op.drop_table('user_spheres')
    op.drop_table('foundation_spheres')
    op.drop_table('company_spheres')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_phone'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_id'))

    op.drop_table('verification_codes')
    op.drop_table('spheres')
    # ### end Alembic commands ###
